apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: fikia-psql-cluster

spec:
  dockerImage: ghcr.io/zalando/spilo-15:2.1-p9
  teamId: "acid"
  numberOfInstances: 2
  enableLogicalBackup: false
  users:  # Application/Robot users
    fikiaadmin:  # database owner
    - superuser
    - createdb

#    flyway: []
#  usersWithSecretRotation:
#  - foo_user
#  usersWithInPlaceSecretRotation:
#  - flyway
#  - bar_owner_user
    fikiabn:
    - login
    - createdb

  databases:
    # foo: zalando  # dbname: owner
    api: fikiabn # dbname: owner

  preparedDatabases: {}
  postgresql:
    version: "15"
    parameters:  # Expert section: use this tool to tweek https://pgtune.leopard.in.ua/
      max_connections : "200"
      shared_buffers : "128MB"
      effective_cache_size : "384MB"
      maintenance_work_mem : "32MB"
      checkpoint_completion_target : "0.9"
      wal_buffers : "3932kB"
      default_statistics_target : "100"
      random_page_cost : "1.1"
      effective_io_concurrency : "200"
      work_mem : "327kB"

  volume:
    size: 500Mi
    storageClass: "do-block-storage-xfs-retain"
  additionalVolumes:
    - name: empty
      mountPath: /opt/empty
      targetContainers:
        - all
      volumeSource:
        emptyDir: {}

  enableShmVolume: true

  resources:
    limits:
      cpu: "1"
      memory: 500Mi
    requests:
      cpu: "200m"
      memory: 250Mi


  patroni:
    synchronous_mode_strict: true
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - host    all             all           0.0.0.0/0               md5
      - host    all             all           ::/0                    md5
      - hostssl all             all           0.0.0.0/0               md5
      - local   all             all                                   trust
      - hostssl all             +zalandos      127.0.0.1/32           pam
      - host    all             all            127.0.0.1/32           md5
      - hostssl all             +zalandos      ::1/128                pam
      - host    all             all            ::1/128                md5
      - hostssl replication     standby        all                    md5
      - hostnossl all           all            all                    reject
      - hostssl all             +zalandos      all                    pam
      - hostssl all             all            all                    md5


  initContainers:
  - name: date
    image: busybox
    command: [ "/bin/date" ]


# Custom TLS certificate. Disabled unless tls.secretName has a value.
  tls:
    secretName: ""  # should correspond to a Kubernetes Secret resource to load
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caFile: ""  # optionally configure Postgres with a CA certificate
    caSecretName: "" # optionally the ca.crt can come from this secret instead.
# file names can be also defined with absolute path, and will no longer be relative
# to the "/tls/" path where the secret is being mounted by default, and "/tlsca/"
# where the caSecret is mounted by default.
# When TLS is enabled, also set spiloFSGroup parameter above to the relevant value.
# if unknown, set it to 103 which is the usual value in the default spilo images.
# In Openshift, there is no need to set spiloFSGroup/spilo_fsgroup.

# Add node affinity support by allowing postgres pods to schedule only on nodes that
# have label: "postgres-operator:enabled" set.
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: postgres-operator
#              operator: In
#              values:
#                - enabled

# Enables change data capture streams for defined database tables
#  streams:
#  - applicationId: test-app
#    database: foo
#    tables:
#      data.state_pending_outbox:
#        eventType: test-app.status-pending
#      data.state_approved_outbox:
#        eventType: test-app.status-approved
#      data.orders_outbox:
#        eventType: test-app.order-completed
#        idColumn: o_id
#        payloadColumn: o_payload
#    # Optional. Filter ignores events before a certain txnId and lsn. Can be used to skip bad events
#    filter:
#      data.orders_outbox: "[?(@.source.txId > 500 && @.source.lsn > 123456)]"
#    batchSize: 1000
