# Token to authenticate vault
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
stringData:
  token: hvs.xD3rB9HzxSybxcBSTXgcHLTP # "root"
---
# create a secret store which specifies how kubernetes will connect to the store
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fikia-vault
spec:
  provider:
    vault:
      server: "http://vault-server.vault:8200"
      path: "kv"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
# Create an external secret object which in turn creates the exact secret you want
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-staging
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: fikia-vault
    kind: SecretStore
  target:
    name: api-staging
  dataFrom:
  - extract:
      key: api-staging
