name: Build
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set released tag in env vars
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Throw error when tag name is invalid
        if: ${{ !(contains(env.RELEASE_VERSION,'-staging')) && !(contains(env.RELEASE_VERSION,'-prod')) }}
        run: |
          exit "Invalid tag name. tag name should end with either -staging or -prod"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/tier-one/be-fikia:${{ github.event.release.tag_name }}
