name: Build and Deploy
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/user/repo:${{ github.event.release.tag_name }}

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v1

    # - name: Set up kubeconfig
    #   run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

    # - name: Deploy to Kubernetes
    #   run: |
    #     helm -n staging-apps upgrade --set --image.tag=${{ github.event.release.tag_name }}
